seed: 42
run_mode: 'eval'
output_dir: './output' # path to save checkpoint/strategy
load_checkpoint: ''
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False

# context
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: str = "--disable_expand_ops=Softmax,Dropout " \
                              "--enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0

# aicc
remote_save_url: "Please input obs url on AICC platform."

# runner
runner_config:
  epochs: 10
  batch_size: 100
  sink_size: 2
  image_size: 224
  sink_mode: False
  initial_epoch: 0
  has_trained_epoches: 0
  has_trained_steps: 0
runner_wrapper:
  type: TrainOneStepCell
  sens: 1024

# parallel
use_parallel: False
parallel:
  parallel_mode: 0 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: True
  enable_alltoall: False
  full_batch: False
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: False
  strategy_ckpt_save_file: "./ckpt_strategy.ckpt"
parallel_config:
  data_parallel: 1
  model_parallel: 1
  expert_parallel: 1
  pipeline_stage: 1
  optimizer_shard: False
  micro_batch_num: 1
  gradient_aggregation_group: 4
micro_batch_interleave_num: 1

# recompute
recompute_config:
  recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: False

# autotune
auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

# profile
profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True

# Trainer
trainer:
  type: image_to_text_retrieval
  model_name: 'blip2_stage1_evaluator'

# eval dataset
eval_dataset: &eval_dataset
  data_loader:
    type: MultiImgCapDataLoader
    dataset_dir: "/data"
    annotation_files: [
      "flickr30k/annotations/test.json"
    ]
    image_dirs: [
      "flickr30k/images"
    ]
    stage: "eval"
    column_names: ["image", "text"]
    shuffle: False
  transforms:
    - type: ToPIL # align with torch impl -> check interaction with 'Resize'
    - type: Resize
      size: [224, 224]
      interpolation: "bicubic"
    - type: ToTensor
    - type: Normalize
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]
      is_hwc: False
  text_transforms:
    type: CaptionTransform
    prompt: ""
    max_words: 50
    max_length: 35
    padding: 'max_length'
    random_seed: 2022
    truncation: True
  tokenizer:
    type: BertTokenizer
    pad_token: '[PAD]'
    bos_token: '[DEC]'
    add_special_tokens: True
    padding: 'max_length'
    truncation: True
    max_length: 35
  k_test: 128 # only top_k takes part in computation
  add_extra_itm_score: True
  num_parallel_workers: 1
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 50
  repeat: 1
  numa_enable: False
  prefetch_size: 30
  seed: 2022
  return_attention_mask: True
eval_dataset_task:
  type: ContrastiveLanguageImagePretrainDataset
  dataset_config: *eval_dataset
# model
model:
  model_config:
    type: Blip2Config
    freeze_vision: True
    max_txt_len: 32
    checkpoint_name_or_path: "blip2_stage1_pretrained" # pretrained model dict here
    dtype: "float32"
    compute_dtype: "float16"
    layernorm_dtype: "float32"
    softmax_dtype: "float32"
    vision_config:
      type: ViTConfig
      image_size: 224
      patch_size: 14
      num_channels: 3
      initializer_range: 0.001
      hidden_size: 1408
      num_hidden_layers: 39
      num_attention_heads: 16
      intermediate_size: 6144
      qkv_bias: true
      hidden_act: gelu
      post_layernorm_residual: false
      layer_norm_eps: 1.0e-6
      attention_probs_dropout_prob: 0.0
      hidden_dropout_prob: 0.0
      drop_path_rate: 0.0
      use_mean_pooling: false
      encoder_stride: 16
      checkpoint_name_or_path: "vit_g_p16"

    qformer_config:
      num_hidden_layers: 12
      num_attention_heads: 12
      query_length: 32
      resize_token_embeddings: True # if run on Atlas 800T A2, turn it to False
      special_token_nums: 1
      vocab_size: 30522
      hidden_size: 768
      encoder_width: 1408
      bos_token_id: 30522
      sep_token_id: 102
      pad_token_id: 0
      max_position_embeddings: 512
      layer_norm_eps: 1.e-12
      hidden_dropout_prob: 0.1
      attention_probs_dropout_prob: 0.1
      chunk_size_feed_forward: 0
      cross_attention_freq: 2
      intermediate_size: 3072
      initializer_range: 0.02
      hidden_act: "gelu"
      dtype: "float32"
      layernorm_dtype: "float32"
      softmax_dtype: "float32"
      compute_dtype: "float16"
      add_cross_attention: True
      use_relative_positions: False
      tie_word_embeddings: True
      output_attentions: False
      output_hidden_states: False
      use_return_dict: False
  arch:
    type: Blip2ItmEvaluator

# lr sechdule
lr_schedule:
  type: cosine
  learning_rate: 1.e-4
  lr_end: 1.e-5
  warmup_lr_init: 1.e-6
  warmup_steps: 5000
  total_steps: -1 # -1 means it will load the total steps of the dataset
layer_scale: False
lr_scale: False

# optimizer
optimizer:
  type: adamw
  beta1: 0.9
  beta2: 0.98
  eps: 1.e-8
  weight_decay: 0.05

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMointor
    prefix: "blip2_stage1_evaluator"
    save_checkpoint_steps: 10000
    integrated_save: True
    async_save: False
  - type: ObsMonitor
eval_callbacks:
  - type: ObsMonitor

# image processor, tokenizer for prediction
processor:
  type: Blip2Processor
  image_processor:
    type: Blip2ImageProcessor
    image_size: 224
    mean: [0.48145466, 0.4578275, 0.40821073]
    std: [0.26862954, 0.26130258, 0.27577711]
    is_hwc: False
  tokenizer:
    type: BertTokenizer
    pad_token: '[PAD]'
    bos_token: '[DEC]'
    add_special_tokens: True
    padding: 'max_length'
    truncation: True
    max_length: 32
