seed: 42
run_mode: 'train'
output_dir: './output' # path to save checkpoint/strategy
load_checkpoint: ''
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False

# context
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: str = "--disable_expand_ops=Softmax,Dropout " \
                              "--enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  max_device_memory: "30GB"
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0

# aicc
remote_save_url: "Please input obs url on AICC platform."

# runner
runner_config:
  epochs: 1
  batch_size: &batch_size 16
  sink_size: 2
  image_size: 224
  sink_mode: True
  initial_epoch: 0
  has_trained_epoches: 0
  has_trained_steps: 0
runner_wrapper:
  type: TrainOneStepCell
  sens: 1024

# parallel
use_parallel: False
parallel:
  parallel_mode: 0 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: False
  full_batch: False
parallel_config:
  data_parallel: 1
  model_parallel: 1
  pipeline_stage: 1
  micro_batch_num: 1
  vocab_emb_dp: True
  gradient_aggregation_group: 4
micro_batch_interleave_num: &micro_batch_interleave_num 1

# recompute
recompute_config:
  recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: False

# autotune
auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

# profile
profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True

# Trainer
trainer:
  type: ContrastiveLanguageImagePretrainTrainer
  model_name: 'blip2_stage2_vit_g_baichuan_7b'

# train dataset
train_dataset: &train_dataset
  data_loader:
    type: MultiImgCapDataLoader
    dataset_dir: "/data"
    annotation_files: [
      "coco2014/coco/annotations/coco_karpathy_train.json"
    ]
    image_dirs: [
      "coco2014/coco/images"
    ]
    stage: "train"
    column_names: ["image", "text"]
    shuffle: True
  transforms:
    - type: RandomResizedCrop
      size: 224
      scale: [0.5, 1.0]
      interpolation: "bicubic"
    - type: RandomHorizontalFlip
    - type: ToTensor
    - type: Normalize
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]
      is_hwc: False
  text_transforms:
    type: CaptionTransform
    prompt: ""
    max_words: 50
    max_length: 33  # it equals to Blip2Config.max_txt_len + 1 for constructing labels
    padding: 'max_length'
    random_seed: 2022
    truncation: True
    add_special_tokens: True
  tokenizer:
    type: LlamaTokenizer
    unk_token: '<unk>'
    bos_token: '<s>'
    eos_token: '</s>'
    pad_token: '<pad>'
    add_special_tokens: False
    padding: 'max_length'
    truncation: True
    max_length: 33  # it equals to Blip2Config.max_txt_len + 1 for constructing labels
    add_bos_token: False
    add_eos_token: True
    vocab_file: ""

  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 4
  repeat: 1
  numa_enable: False
  prefetch_size: 30
  seed: 2022
train_dataset_task:
  type: ContrastiveLanguageImagePretrainDataset
  dataset_config: *train_dataset
# model
model:
  model_config:
    type: Blip2Config
    batch_size: *batch_size
    micro_batch_interleave_num: *micro_batch_interleave_num
    freeze_vision: True
    freeze_text: True
    max_txt_len: 32
    checkpoint_name_or_path: ""
    dtype: "float32"
    compute_dtype: "float16"
    layernorm_dtype: "float32"
    softmax_dtype: "float32"
    prompt: False
    prompt_length: 0
    vision_config:
      type: ViTConfig
      image_size: 224
      patch_size: 14
      num_channels: 3
      initializer_range: 0.001
      hidden_size: 1408
      num_hidden_layers: 39
      num_attention_heads: 16
      intermediate_size: 6144
      qkv_bias: True
      hidden_act: gelu
      post_layernorm_residual: false
      layer_norm_eps: 1.0e-6
      attention_probs_dropout_prob: 0.0
      hidden_dropout_prob: 0.0
      drop_path_rate: 0.0
      use_mean_pooling: false
      encoder_stride: 16
      checkpoint_name_or_path: "vit_g_p16"

    qformer_config:
      vocab_size: 44728

    text_config:
      type: LlamaConfig
      seq_length: 64  # sum of max_txt_len and num_query_token
      hidden_size: 4096
      num_layers: 32
      num_heads: 32
      vocab_size: 64001
      multiple_of: 256
      rms_norm_eps: 1.0e-6
      bos_token_id: 1
      eos_token_id: 2
      pad_token_id: 0
      ignore_token_id: -100
      compute_dtype: "float16"
      layernorm_compute_type: "float32"
      softmax_compute_type: "float32"
      rotary_dtype: "float16"
      param_init_type: "float16"
      use_past: False
      offset: 0
      repetition_penalty: 1
      max_decode_length: 512
      top_k: 3
      top_p: 1
      do_sample: False
      checkpoint_name_or_path: ""
  arch:
    type: Blip2Llm

# lr schedule
lr_schedule:
  type: CosineWithWarmUpLR
  learning_rate: 1.e-4
  lr_end: 1.e-5
  warmup_lr_init: 1.e-6
  warmup_steps: 2000
  total_steps: -1 # -1 means it will load the total steps of the dataset
layer_scale: False
layer_decay: 0.65
lr_scale: False
lr_scale_factor: 256

# optimizer
optimizer:
  type: FP32StateAdamWeightDecay
  beta1: 0.9
  beta2: 0.98
  eps: 1.e-8 # 1e-8
  weight_decay: 0.05
  learning_rate: 1.e-4

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMointor
    prefix: "blip2_stage2_vig_g_baichuan_7b"
    save_checkpoint_steps: 10000
    integrated_save: True
    async_save: False
  - type: ObsMonitor
eval_callbacks:
  - type: ObsMonitor


# processor
processor:
  type: Blip2Processor
  image_processor:
    type: Blip2ImageProcessor
    image_size: 224  # input image size
  tokenizer:
    type: LlamaTokenizer
    pad_token: '<pad>'
    bos_token: '<s>'
    unk_token: '</s>'
    eos_token: '</s>'
    add_special_tokens: False
    padding: 'max_length'
    truncation: True
    max_length: 32
