base_config: [
    './task_config/context.yaml',
    './task_config/runner.yaml',
    './task_config/bert_mnli_dataset.yaml',
    './model_config/txtcls_bert_base_uncased_mnli.yaml',
    '../__base__.yaml' ]

profile: False
use_parallel: False

seed: 42
resume_or_finetune_checkpoint: ''

top_k: 1

run_mode: 'train'
trainer:
  type: TextClassificationTrainer
  model_name: txtcls_bert_base_uncased_mnli
