seed: 0
run_mode: 'train'
output_dir: './output' # path to save checkpoint/strategy
load_checkpoint: ""
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False

# context
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--disable_expand_ops=Softmax,Dropout --enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  max_device_memory: "31GB"
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0

# aicc
remote_save_url: "Please input obs url on AICC platform."

# runner
runner_config:
  epochs: 2
  batch_size: 8
  sink_mode: True
  sink_size: 2
runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 4294967296
    scale_factor: 2
    scale_window: 1000
  use_clip_grad: True

# parallel
use_parallel: True
parallel:
  parallel_mode: 1 # 0-data parallel, 1-semi-auto parallel, 2-auto parallel, 3-hybrid parallel
  gradients_mean: False
  loss_repeated_mean: True
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True
  strategy_ckpt_save_file: "./ckpt_strategy.ckpt"
# dp 4 mp 4 pp 1 for 2 nodes 16 devices micro_batch_num 1
# dp 4 mp 2 pp 4 for 4 nodes 32 devices micro_batch_num 32
# dp 16 mp 1 pp 8 for 16 nodes 128 devices micro_batch_num 80
parallel_config:
  data_parallel: 4
  model_parallel: 4
  pipeline_stage: 1
  micro_batch_num: 1
  vocab_emb_dp: True
  gradient_aggregation_group: 4
micro_batch_interleave_num: 1

# moe
moe_config:
  expert_num: 1
  capacity_factor: 1.05
  aux_loss_factor: 0.05
  num_experts_chosen: 1

# recompute
recompute_config:
  recompute: True
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: False

# autotune
auto_tune: True
filepath_prefix: './autotune'
autotune_per_step: 10

# profile
profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: True
profile_communication: True
profile_memory: True

# Trainer
trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'pangualpha_13b'
# if True, do evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: False

# train dataset
train_dataset: &train_dataset
  data_loader:
    type: MindDataset
    dataset_dir: ""
    shuffle: True
  input_columns: ["input_ids"]
  output_columns: ["input_ids", "position_id", "attention_mask"]
  eod_reset: True
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 8
  repeat: 1
  numa_enable: False
  prefetch_size: 1
train_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *train_dataset

eval_dataset: &eval_dataset
  data_loader:
    type: MindDataset
    dataset_dir: ""
    shuffle: True
  input_columns: ["input_ids"]
  output_columns: ["input_ids", "position_id", "attention_mask"]
  eod_reset: False
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 8
  repeat: 1
  numa_enable: False
  prefetch_size: 1
eval_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *eval_dataset

# model
model:
  model_config:
    type: PanguAlphaConfig
    batch_size: 1
    seq_length: 1024
    vocab_size: 40000
    hidden_size: 5120
    ffn_hidden_size: 20480
    num_layers: 40
    num_heads: 40
    pad_token_id: 6
    eod_token_id: 6
    eos_token_id: 9
    post_layernorm_residual: False
    param_init_type: 'float32'
    compute_dtype: 'float16'
    softmax_compute_type: 'float16'
    embedding_dropout_prob: 0.1
    hidden_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    hidden_act: 'fast_gelu'
    use_past: False
    use_moe: False
    expert_num: 1
    per_token_num_experts_chosen: 1
    checkpoint_name_or_path: "pangualpha_13b"
    repetition_penalty: 1
    max_decode_length: 1024
    top_k: 5
    top_p: 1
    do_sample: True
  arch:
    type: PanguAlphaHeadModel

# lr sechdule
lr_schedule:
  type: polynomial
  learning_rate: 0.00005
  lr_end: 0.000001
  warmup_steps: 2000
  total_steps: -1 # -1 means it will load the total steps of the dataset
layer_scale: False
layer_decay: 0.65
lr_scale: False
lr_scale_factor: 256

# optimizer
optimizer:
  type: FP32StateAdamWeightDecay
  beta1: 0.9
  beta2: 0.95
  eps: 0.00000001 # 1e-8
  weight_decay: 0.1

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: CheckpointMointor
    prefix: "PanguAlpha-13b"
    save_checkpoint_steps: 500
    integrated_save: False
    async_save: False
  - type: ObsMonitor
eval_callbacks:
  - type: ObsMonitor

# metric
metric:
  type: PerplexityMetric

# processor
processor:
  return_tensors: ms
  tokenizer:
    type: PanguAlphaTokenizer
  type: PanguAlphaProcessor