seed: 0
run_mode: 'predict'
output_dir: './output' # path to save checkpoint/strategy
load_checkpoint: ''
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed model
only_save_strategy: False
resume_training: False

# context
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--opt_level=0"
  max_call_depth: 10000
  save_graphs: False
  device_id: 0

# aicc
remote_save_url: "Please input obs url on AICC platform."

# runner
runner_config:
  epochs: 100
  batch_size: 32
  image_size: 224
  sink_mode: True
  sink_size: 2
  num_classes: 1000
runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: FixedLossScaleUpdateCell
    loss_scale_value: 1024

# parallel
use_parallel: False
parallel:
  parallel_mode: 0 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: True
  enable_alltoall: False
  full_batch: False
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: False
  strategy_ckpt_save_file: "./ckpt_strategy.ckpt"
parallel_config:
  data_parallel: 1
  model_parallel: 1
  expert_parallel: 1
  pipeline_stage: 1
  micro_batch_num: 1
  gradient_aggregation_group: 4
micro_batch_interleave_num: 1

# moe
moe_config:
  expert_num: 1
  capacity_factor: 1.05
  aux_loss_factor: 0.05
  num_experts_chosen: 1

# recompute
recompute_config:
  recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: False

# autotune
auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

# profile
profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True

# Trainer
trainer:
  type: image_segmentation
  model_name: 'vit_base_p16'
# if True, do evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: False
eval_step_interval: -1        # num of step intervals between each eval, -1 means no step end eval.
eval_epoch_interval: 50        # num of epoch intervals between each eval, 1 means eval on every epoch end.

# train dataset
train_dataset: &train_dataset
  seed: 2022
  batch_size: 32
  data_loader:
    type: ImageFolderDataset
    dataset_dir: "imageNet-1k/train"
    num_parallel_workers: 8
    shuffle: True
  transforms:
    - type: Decode
    - type: RandomResizedCrop
      size: 224
      scale: [0.08, 1.0]
      interpolation: cubic
    - type: RandomHorizontalFlip
      prob: 0.5
    - type: ToPIL
    - type: rand_augment_transform
      config_str: "rand-m9-mstd0.5-inc1"
      hparams:
        translate_const: 100
        img_mean: [124, 116, 104]
        interpolation: cubic
    - type: ToTensor
    - type: Normalize
      mean: [0.485, 0.456, 0.406] # [123.675, 118.575, 103.53]
      std: [0.229, 0.224, 0.225] #
      is_hwc: False
    - type: RandomErasing
      probability: 0.25
      mode: pixel
      max_count: 1
  mixup_op:
    mixup_alpha: 0.8
    cutmix_alpha: 1.0
    cutmix_minmax:
    prob: 1.0
    switch_prob: 0.5
    label_smoothing: 0.1
  input_columns: ["image", "label"]
  output_columns: ["image", "label"]
  column_order: ["image", "label"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  repeat: 1
  numa_enable: False
  prefetch_size: 30
train_dataset_task:
  type: ImageCLSDataset
  dataset_config: *train_dataset

# eval dataset
eval_dataset: &eval_dataset
  seed: 2022
  batch_size: 32
  data_loader:
    type: ImageFolderDataset
    dataset_dir: "imageNet-1k/val"
    num_parallel_workers: 8
    shuffle: True
  transforms:
    - type: Decode
    - type: Resize
      size: 256
      interpolation: cubic
    - type: CenterCrop
      size: 224
    - type: ToTensor
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_hwc: False
  input_columns: ["image", "label"]
  output_columns: ["image", "label"]
  column_order: ["image", "label"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  repeat: 1
  numa_enable: False
  prefetch_size: 30
  eval_interval: 1
  eval_offset: 0
eval_dataset_task:
  type: ImageCLSDataset
  dataset_config: *eval_dataset

# model
model:
  arch:
    type: SamModel
  model_config:
    type: SamConfig
    image_encoder:
      arch:
        type: SamImageEncoder
      model_config:
        type: ImageEncoderConfig
        img_size: 1024
        patch_size: 16
        in_chans: 3
        embed_dim: 1024
        depth: 24
        num_heads: 16
        mlp_ratio: 4
        out_chans: 256
        qkv_bias: True
        use_abs_pos: True
        use_rel_pos: True # 仅支持默认False
        rel_pos_zero_init: True
        window_size: 14
        global_attn_indexes: [5, 11, 17, 23]
        layer_norm_eps: 1.e-12
        compute_dtype: "float16"
        layernorm_compute_type: "float32"
        softmax_compute_type: "float32"
    prompt_config:
      arch:
        type: SamPromptEncoder
      model_config:
        type: PromptEncoderConfig
        prompt_embed_dim: 256
        image_embedding_size: [64, 64]
        input_image_size: [1024, 1024]
        mask_in_chans: 16
        compute_dtype: "float16"
    decoder_config:
      arch:
        type: SamMaskDecoder
      model_config:
        type: MaskDecoderConfig
        num_multimask_outputs: 3
        # transformer:
        decoder_depth: 2
        decoder_embed_dim: 256
        decoder_mlp_dim: 2048
        decoder_num_heads: 8
        transformer_dim: 256
        iou_head_depth: 3
        iou_head_hidden_dim: 256
        layer_norm_eps: 1.e-12
        compute_dtype: "float16"
        layernorm_compute_type: "float32"
        softmax_compute_type: "float32"
    # std
    checkpoint_name_or_path: "sam_vit_l"

# lr sechdule
lr_schedule:
  type: cosine
  learning_rate: 0.0005
  lr_end: 0.000001
  warmup_epochs: 5
  total_steps: -1 # -1 means it will load the total steps of the dataset
layer_scale: True
layer_decay: 0.65

# optimizer
optimizer:
  type: adamw
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001 # 1e-8
  weight_decay: 0.05
lr_scale: True
lr_scale_factor: 256

# callbacks
callbacks:
  - type: MFLossMonitor
  - type: SummaryMonitor
    keep_default_action: True
  - type: CheckpointMointor
    prefix: "mindformers"
    save_checkpoint_steps: 100
    integrated_save: True
    async_save: False
  - type: ObsMonitor
eval_callbacks:
  - type: ObsMonitor

# metric
metric:
  type: Accuracy
  eval_type: classification

# processor
processor:
  type: SamProcessor
  image_processor:
    type: SamImageProcessor
    img_size: 1024  # input image size: int or [h, w] or (h, w)
    mean: [123.675, 116.28, 103.53]
    std: [58.395, 57.12, 57.375]
