llama:
  input_path:
  output_path:
  dtype:

glm:
  input_path:
  output_path:
  dtype:

qwen:
  input_path:
  output_path:
  dtype:

internlm:
  input_path:
  output_path:
  dtype:

baichuan:
  input_path:
  output_path:
  dtype:

gpt:
  input_path:
  output_path:
  dtype:

bloom:
  input_path:
  output_path:
  dtype:
  n_head: 16 # 16 for bloom_560m or 32 for bloom_7.1b
  hidden_size: 1024 # 1024 for bloom_560m or 4096 for bloom_7.1b

blip:
  input_path:
  output_path:
  dtype:

wizardcoder:
  input_path:
  output_path:
  dtype:

skywork:
  input_path:
  output_path:
  dtype: