llama:
  input_path:
  output_path:
  dtype:

glm:
  input_path:
  output_path:
  dtype:

qwen:
  input_path:
  output_path:
  dtype:

internlm:
  input_path:
  output_path:
  dtype:

baichuan:
  input_path:
  output_path:
  dtype:

gpt:
  input_path:
  output_path:
  dtype:

blip:
  input_path:
  output_path:
  dtype:

wizardcoder:
  input_path:
  output_path:
  dtype:

glm2:
  input_path:
  output_path:
  dtype:
  model_class: AutoModel

mae:
  input_path:
  output_path:
  dtype:

vit:
  input_path:
  output_path:
  dtype:

swin:
  input_path:
  output_path:
  dtype:

knowlm:
  input_path:
  output_path:
  dtype:

